"""Standalone, standard-library-only receiver for immutable static publications.

Install this file on the publishing host; it deliberately imports no Hortator
modules and has no credentials. SSH authenticates the trusted local worker.
Model tools never invoke this receiver or choose its bot_id themselves.

Usage: python3 publishing_receiver.py --web-root /srv/www/council \
    --state-root /srv/council-publishing deploy|status|audit
Deploy/status read one bounded JSON object from stdin. Audit needs no stdin.
"""

from __future__ import annotations

import argparse
import base64
import binascii
from contextlib import contextmanager
from datetime import datetime, timezone
import fcntl
import hashlib
import json
import math
import os
from pathlib import Path, PurePosixPath
import re
import secrets
import shutil
import stat
import subprocess
import sys


MAX_FILE = 8_000_000
MAX_SITE = 50_000_000
MAX_BOT = 250_000_000
MAX_FILES = 100
MAX_SITES = 100
MAX_ENVELOPE = 70_000_000
STATIC_EXTENSIONS = {
    ".html",
    ".htm",
    ".css",
    ".js",
    ".mjs",
    ".json",
    ".txt",
    ".md",
    ".csv",
    ".tsv",
    ".svg",
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".gif",
    ".avif",
    ".ico",
    ".pdf",
    ".xml",
    ".wasm",
    ".mp3",
    ".wav",
    ".ogg",
    ".mp4",
    ".webm",
    ".woff",
    ".woff2",
    ".ttf",
    ".zip",
    ".yaml",
    ".yml",
    ".ics",
    ".bin",
}
BOT_PATTERN = re.compile(r"[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}")
SLUG_PATTERN = re.compile(r"[a-z0-9][a-z0-9-]{0,63}")
JOB_PATTERN = re.compile(r"[a-zA-Z0-9][a-zA-Z0-9_-]{0,127}")
HASH_PATTERN = re.compile(r"[a-f0-9]{64}")
PROGRAM_SUFFIX = re.compile(
    r"\.(?:php\d*|phtml|phar|cgi|fcgi|pl|py|rb|sh|bash|shtml|shtm|asp|aspx)(?:\.|$)", re.I
)
OWNER_FILE = ".hortator-owner.json"

# Generated by the receiver, never supplied by a bot. Keeping these rules in
# each reserved namespace leaves unrelated files at the domain root untouched.
HTACCESS = """# Managed by Hortator static publishing; do not edit generated namespaces.
Options -Indexes -ExecCGI -Includes +FollowSymLinks
DirectoryIndex index.html index.htm
SetHandler default-handler
RewriteEngine On
RewriteRule ^$ - [R=404,L]
<FilesMatch "^\\.">
    Require all denied
</FilesMatch>
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "no-referrer"
    Header always set X-Frame-Options "DENY"
    Header always set Cross-Origin-Opener-Policy "same-origin"
    Header always set Access-Control-Allow-Origin "*"
    Header always set Cache-Control "no-store"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    Header always set Content-Security-Policy "sandbox allow-scripts; default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; media-src 'self'; connect-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"
</IfModule>
"""


class ReceiverError(Exception):
    """A bounded, operator-readable refusal, safe to return over SSH."""


def canonical(value) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
    ).encode()


def digest(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def safe_path(value) -> bool:
    return (
        isinstance(value, str)
        and 0 < len(value) <= 240
        and not value.startswith("/")
        and "\\" not in value
        and not any(ord(c) < 32 or ord(c) == 127 for c in value)
        and all(
            p and not p.startswith(".") and re.fullmatch(r"[A-Za-z0-9_. -]+", p) for p in value.split("/")
        )
        and PurePosixPath(value).suffix.lower() in STATIC_EXTENSIONS
        and not PROGRAM_SUFFIX.search(value)
    )


def validate_envelope(payload: dict) -> tuple[dict, dict[str, bytes]]:
    """Validate everything before reserving a name or writing any publication."""
    errors = []
    if not isinstance(payload, dict):
        raise ReceiverError("Publish request must be a JSON object.")
    required = {
        "version",
        "bot_id",
        "slug",
        "revision",
        "job_id",
        "turn_id",
        "created_at",
        "files",
        "local_snapshot_commit",
    }
    if set(payload) != required:
        if required - payload.keys():
            errors.append("Missing fields: " + ", ".join(sorted(required - payload.keys())))
        if payload.keys() - required:
            errors.append("Unknown fields are not accepted.")
    if type(payload.get("version")) is not int or payload["version"] != 1:
        errors.append("version must be integer 1")
    for field, pattern in (("bot_id", BOT_PATTERN), ("slug", SLUG_PATTERN), ("job_id", JOB_PATTERN)):
        if not isinstance(payload.get(field), str) or not pattern.fullmatch(payload[field]):
            errors.append(f"{field} must be a valid, nonempty stable identifier")
    if type(payload.get("revision")) is not int or not 1 <= payload["revision"] <= 2**53 - 1:
        errors.append("revision must be a positive integer")
    turn = payload.get("turn_id")
    if not isinstance(turn, str) or len(turn) > 128 or (turn and not JOB_PATTERN.fullmatch(turn)):
        errors.append("turn_id must be an identifier up to 128 characters, or an empty string")
    created = payload.get("created_at")
    valid_date = type(created) in (int, float) and 0 <= created <= 253402300799 and math.isfinite(created)
    if isinstance(created, str) and 0 < len(created) <= 64:
        try:
            valid_date = datetime.fromisoformat(created.replace("Z", "+00:00")).tzinfo is not None
        except ValueError:
            pass
    if not valid_date:
        errors.append("created_at must be a finite Unix timestamp or ISO timestamp with timezone")
    commit = payload.get("local_snapshot_commit")
    if not isinstance(commit, str) or not re.fullmatch(r"[a-f0-9]{40}(?:[a-f0-9]{24})?", commit):
        errors.append("local_snapshot_commit must identify the existing local Git snapshot")
    files = payload.get("files")
    if not isinstance(files, dict) or not 1 <= len(files) <= MAX_FILES:
        errors.append(f"files must contain between 1 and {MAX_FILES} static paths")
        files = {}
    content, manifest, total = {}, {}, 0
    for path, item in files.items():
        label = path[:240] if isinstance(path, str) else "(invalid path)"
        if not safe_path(path):
            errors.append(f"{label}: use a relative static path; no dotfiles, traversal or server programs")
        if not isinstance(item, dict) or set(item) != {"blob", "bytes", "mime", "content"}:
            errors.append(f"{label}: file needs exactly blob, bytes, mime and base64 content")
            continue
        blob, size, mime, encoded = (item.get(k) for k in ("blob", "bytes", "mime", "content"))
        if not isinstance(blob, str) or not HASH_PATTERN.fullmatch(blob):
            errors.append(f"{label}: blob must be a lowercase SHA256 hash")
        if type(size) is not int or not 0 <= size <= MAX_FILE:
            errors.append(f"{label}: bytes must be an integer between 0 and {MAX_FILE}")
        if not isinstance(mime, str) or not 1 <= len(mime) <= 200 or any(ord(c) < 32 for c in mime):
            errors.append(f"{label}: mime must be a bounded media type string")
        try:
            if not isinstance(encoded, str) or len(encoded) > (MAX_FILE + 2) // 3 * 4:
                raise ValueError
            data = base64.b64decode(encoded, validate=True)
        except (binascii.Error, ValueError):
            errors.append(f"{label}: content must be valid bounded base64")
            continue
        total += len(data)
        if len(data) != size:
            errors.append(f"{label}: bytes does not match the decoded file length")
        if digest(data) != blob:
            errors.append(f"{label}: blob does not match the decoded file SHA256")
        content[path] = data
        manifest[path] = {"blob": blob, "bytes": size, "mime": mime}
    if total > MAX_SITE:
        errors.append(f"Combined site files exceed {MAX_SITE} bytes")
    # A file cannot also be the directory containing another file.
    paths = set(files)
    for path in paths:
        if isinstance(path, str) and any(
            str(p) in paths for p in PurePosixPath(path).parents if str(p) != "."
        ):
            errors.append(f"{path[:240]}: a parent path is already a file")
    if errors:
        raise ReceiverError("Invalid publish request:\n- " + "\n- ".join(errors))
    record = {k: v for k, v in payload.items() if k != "files"}
    record["manifest"] = manifest
    record["manifest_hash"] = digest(canonical(manifest))
    record["envelope_hash"] = digest(canonical(record))
    return record, content


def _no_symlink_ancestors(path: Path):
    for part in (*reversed(path.parents), path):
        if part.is_symlink():
            raise ReceiverError("Publishing paths must not traverse symbolic links.")


def _directory(path: Path, mode=0o700):
    _no_symlink_ancestors(path)
    if path.exists():
        if not path.is_dir() or path.stat().st_uid != os.getuid():
            raise ReceiverError("A publishing directory has an unexpected type or owner.")
    else:
        path.mkdir(mode=mode)
    path.chmod(mode)


def _sync_directory(path: Path):
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _read(path: Path, limit=MAX_ENVELOPE) -> bytes:
    _no_symlink_ancestors(path)
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    try:
        if not stat.S_ISREG(os.fstat(fd).st_mode):
            raise ReceiverError("A publishing file has an unexpected type.")
        with os.fdopen(fd, "rb", closefd=False) as stream:
            data = stream.read(limit + 1)
        if len(data) > limit:
            raise ReceiverError("A publishing file exceeds its size bound.")
        return data
    finally:
        os.close(fd)


def _json(path: Path):
    try:
        value = json.loads(_read(path))
        if not isinstance(value, dict):
            raise ValueError("metadata must be an object")
        return value
    except (ValueError, UnicodeDecodeError) as exc:
        raise ReceiverError("Stored publisher metadata is invalid; nothing was overwritten.") from exc


def _atomic_write(path: Path, data: bytes, mode=0o600):
    _no_symlink_ancestors(path)
    if path.exists() and not path.is_file():
        raise ReceiverError("A managed file has an unexpected type; nothing was overwritten.")
    temporary = path.parent / (".write-" + secrets.token_hex(12))
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    try:
        with os.fdopen(fd, "wb", closefd=False) as stream:
            stream.write(data)
            stream.flush()
            os.fsync(fd)
        os.fchmod(fd, mode)
        os.replace(temporary, path)
        _sync_directory(path.parent)
    finally:
        os.close(fd)
        if temporary.exists():
            temporary.unlink()  # Only our own incomplete temporary file.


def _write_json(path: Path, value):
    _atomic_write(path, canonical(value) + b"\n")


class Receiver:
    def __init__(self, web_root: str | Path, state_root: str | Path):
        self.web = Path(os.path.abspath(web_root))
        self.state = Path(os.path.abspath(state_root))
        if (
            self.state == self.web
            or self.state.is_relative_to(self.web)
            or self.web.is_relative_to(self.state)
        ):
            raise ReceiverError(
                "The private publisher state and public web root must be separate directories."
            )
        _no_symlink_ancestors(self.web)
        _no_symlink_ancestors(self.state)
        if not self.web.is_dir():
            raise ReceiverError("The configured web root must already exist.")
        if not self.state.parent.is_dir():
            raise ReceiverError("The publisher state parent must already exist.")
        self.metadata = self.state / "metadata"
        self.releases = self.state / "releases"
        self.history = self.state / "history"

    @contextmanager
    def locked(self):
        _directory(self.state, 0o755)  # Apache must traverse this ancestor of immutable static releases.
        lock = self.state / ".receiver.lock"
        _no_symlink_ancestors(lock)
        fd = os.open(lock, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW, 0o600)
        try:
            fcntl.flock(fd, fcntl.LOCK_EX)
            _directory(self.metadata)
            root_file = self.metadata / "publisher.json"
            if not root_file.exists():
                if any(self.metadata.iterdir()) or self.releases.exists() or self.history.exists():
                    raise ReceiverError("Unregistered publisher state already exists; it was not adopted.")
                _write_json(
                    root_file, {"version": 1, "web_root": str(self.web), "identity": secrets.token_hex(24)}
                )
            self.root = _json(root_file)
            if (
                self.root.get("version") != 1
                or self.root.get("web_root") != str(self.web)
                or not isinstance(self.root.get("identity"), str)
                or not re.fullmatch(r"[a-f0-9]{48}", self.root["identity"])
            ):
                raise ReceiverError("This publisher state belongs to another web root.")
            for directory in (self.metadata / "bots", self.metadata / "sites", self.metadata / "jobs"):
                _directory(directory)
            _directory(self.releases, 0o755)
            self._init_history()
            yield
        finally:
            fcntl.flock(fd, fcntl.LOCK_UN)
            os.close(fd)

    def _git(self, *args, check=True) -> str:
        executable = shutil.which("git")
        if not executable:
            raise ReceiverError("Git is required for a snapshot before publication.")
        env = {
            "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
            "LC_ALL": "C",
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_CONFIG_GLOBAL": "/dev/null",
            "GIT_ATTR_NOSYSTEM": "1",
        }
        try:
            result = subprocess.run(
                [
                    executable,
                    "-c",
                    "core.hooksPath=/dev/null",
                    "-c",
                    "core.fsmonitor=false",
                    "-c",
                    "user.name=Hortator publishing",
                    "-c",
                    "user.email=publishing@localhost",
                    *args,
                ],
                cwd=self.history,
                env=env,
                capture_output=True,
                timeout=120,
                text=True,
            )
        except subprocess.TimeoutExpired as exc:
            raise ReceiverError("Git snapshot timed out; publication was not acknowledged.") from exc
        if check and result.returncode:
            raise ReceiverError("Git snapshot failed; publication was not acknowledged.")
        return result.stdout.strip() if result.returncode == 0 else ""

    def _init_history(self):
        _directory(self.history)
        if not (self.history / ".git").exists():
            if any(self.history.iterdir()):
                raise ReceiverError("Unmanaged history files already exist; they were not adopted.")
            self._git("-c", "init.templateDir=", "init", "--initial-branch=snapshots")
        _no_symlink_ancestors(self.history / ".git")
        if not (self.history / ".git").is_dir() or self._git("remote"):
            raise ReceiverError("Publisher history must be a dedicated local repository without remotes.")
        for directory in ("sites", "deployments", "audits", "drift"):
            _directory(self.history / directory)

    def _owner(self, bot):
        return {"version": 1, "bot_id": bot, "publisher": self.root["identity"]}

    def _namespace(self, bot, *, create):
        registration = self.metadata / "bots" / (bot + ".json")
        public = self.web / bot
        expected = self._owner(bot)
        if not registration.exists():
            if not create:
                return False
            if os.path.lexists(public):
                raise ReceiverError(
                    "That bot namespace already exists outside this publisher; it cannot be overwritten."
                )
            _write_json(registration, expected)
        if _json(registration) != expected:
            raise ReceiverError("This bot namespace is owned by another identity; it cannot be overwritten.")
        site_directory = self.metadata / "sites" / bot
        _no_symlink_ancestors(site_directory)
        empty_reservation = not site_directory.exists() or not any(site_directory.iterdir())
        if not os.path.lexists(public) and create and empty_reservation:
            # mkdir never replaces an unrelated empty directory, unlike rename.
            # A crash after recording the private reservation can resume only
            # while no public namespace and no site registrations exist.
            public.mkdir(mode=0o755)
            public.chmod(0o755)
            _write_json(public / OWNER_FILE, expected)
            _atomic_write(public / ".htaccess", HTACCESS.encode(), 0o644)
            _sync_directory(self.web)
        _no_symlink_ancestors(public)
        if (
            not public.is_dir()
            or public.stat().st_uid != os.getuid()
            or not (public / OWNER_FILE).exists()
            or _json(public / OWNER_FILE) != expected
        ):
            raise ReceiverError(
                "This bot namespace has missing or foreign ownership metadata; it was not adopted. "
                "If setup was interrupted, the operator must inspect the reserved folder before retrying."
            )
        if (
            create
            and empty_reservation
            and not os.path.lexists(public / ".htaccess")
            and {path.name for path in public.iterdir()} == {OWNER_FILE}
        ):
            _atomic_write(public / ".htaccess", HTACCESS.encode(), 0o644)
        if _read(public / ".htaccess", 16000) != HTACCESS.encode():
            raise ReceiverError(
                "The namespace's static serving rules changed; inspect them before publishing."
            )
        _directory(self.metadata / "sites" / bot)
        _directory(self.releases / bot, 0o755)
        return True

    def _site(self, bot, slug, *, create):
        path = self.metadata / "sites" / bot / (slug + ".json")
        if not path.exists():
            if not create:
                return None
            if os.path.lexists(self.web / bot / slug):
                raise ReceiverError(
                    "That site name is already taken by unmanaged content; choose another site slug."
                )
            if len(list(path.parent.glob("*.json"))) >= MAX_SITES:
                raise ReceiverError("This bot has reached its remote site count limit.")
            _write_json(path, {"version": 1, "owner": bot, "slug": slug, "current": None, "pending": None})
        value = _json(path)
        if value.get("version") != 1 or value.get("owner") != bot or value.get("slug") != slug:
            raise ReceiverError("This site belongs to another bot; it cannot be overwritten.")
        return value

    def _save_site(self, bot, slug, site):
        _write_json(self.metadata / "sites" / bot / (slug + ".json"), site)

    def _job_path(self, job):
        return self.metadata / "jobs" / (digest(job.encode()) + ".json")

    def _record(self, job):
        path = self._job_path(job)
        return _json(path) if path.exists() else None

    def _release_path(self, record):
        # Derive it from validated ownership/job fields; never trust a stored filesystem path.
        return (
            self.releases
            / record["bot_id"]
            / record["slug"]
            / (str(record["revision"]) + "-" + digest(record["job_id"].encode())[:24])
        )

    def _verify_pointer(self, bot, slug, site):
        public = self.web / bot / slug
        allowed = []
        for key in ("current", "pending"):
            if site.get(key):
                record = self._record(site[key])
                if not record or record["bot_id"] != bot or record["slug"] != slug:
                    raise ReceiverError("Site ownership history is inconsistent; publication was refused.")
                allowed.append(str(self._release_path(record)))
        if not os.path.lexists(public):
            if site.get("current"):
                raise ReceiverError(
                    "The published site link is missing; inspect remote drift before publishing."
                )
            return
        if not public.is_symlink() or os.readlink(public) not in allowed:
            raise ReceiverError(
                "The site destination changed or belongs to other content; it cannot be overwritten."
            )

    def _inspect_release(self, record) -> tuple[list[str], dict[str, bytes]]:
        root = self._release_path(record)
        _no_symlink_ancestors(root)
        if not root.is_dir():
            return ["release directory missing"], {}
        found, issues, changed = set(), [], {}
        count, total = 0, 0
        for parent, directories, names in os.walk(root, followlinks=False):
            for name in list(directories):
                path = Path(parent) / name
                if path.is_symlink():
                    issues.append(str(path.relative_to(root)) + ": unexpected symlink")
                    directories.remove(name)
            for name in names:
                path = Path(parent) / name
                relative = str(path.relative_to(root))
                found.add(relative)
                count += 1
                if count > MAX_FILES * 2:
                    issues.append("too many unexpected files; further inspection bounded")
                    return sorted(issues), changed
                if path.is_symlink() or not path.is_file():
                    issues.append(relative + ": unexpected symlink or special file")
                    continue
                if path.stat().st_nlink != 1:
                    issues.append(relative + ": unexpected hard link; content was not read")
                    continue
                if path.stat().st_size > MAX_FILE or total + path.stat().st_size > MAX_SITE:
                    issues.append(relative + ": unexpected size exceeds inspection bound")
                    continue
                data = _read(path, MAX_FILE)
                total += len(data)
                expected = record["manifest"].get(relative)
                if expected is None or len(data) != expected["bytes"] or digest(data) != expected["blob"]:
                    issues.append(
                        relative + ": " + ("unexpected file" if expected is None else "content hash changed")
                    )
                    if safe_path(relative):
                        changed[relative] = data
        issues.extend(path + ": published file missing" for path in record["manifest"] if path not in found)
        return sorted(issues), changed

    def _verify_release(self, record):
        issues, _ = self._inspect_release(record)
        if issues:
            raise ReceiverError("Remote release drift detected: " + "; ".join(issues[:10]))

    def _write_release(self, record, content):
        target = self._release_path(record)
        _directory(target.parent, 0o755)
        if os.path.lexists(target):
            self._verify_release(record)
            return
        temporary = target.parent / (".staging-" + secrets.token_hex(16))
        _directory(temporary, 0o755)
        for path, data in sorted(content.items()):
            destination = temporary / path
            for ancestor in reversed(destination.parent.parents):
                if ancestor != temporary and ancestor.is_relative_to(temporary):
                    _directory(ancestor, 0o755)
            _directory(destination.parent, 0o755)
            _atomic_write(destination, data, 0o644)
        for parent, _, _ in os.walk(temporary, topdown=False):
            _sync_directory(Path(parent))
        if os.path.lexists(target):
            raise ReceiverError("A release name appeared unexpectedly; it was not overwritten.")
        os.rename(temporary, target)
        _sync_directory(target.parent)
        self._verify_release(record)

    def _history_files(self, root: Path, content: dict[str, bytes]):
        for path, data in sorted(content.items()):
            destination = root / path
            for ancestor in reversed(destination.parent.parents):
                if ancestor != self.history and ancestor.is_relative_to(self.history):
                    _directory(ancestor)
            _directory(destination.parent)
            _atomic_write(destination, data)

    def _snapshot(self, record, content):
        snapshot = {k: v for k, v in record.items() if k not in {"status", "remote_commit", "delivered_at"}}
        relative = "deployments/" + digest(record["job_id"].encode()) + ".json"
        destination = self.history / relative
        if destination.exists():
            if _json(destination) != snapshot:
                raise ReceiverError("This job's immutable Git snapshot differs; it was not overwritten.")
            commit = self._git("log", "-1", "--format=%H", "--", relative, check=False)
            if commit:
                if self._git("status", "--porcelain", "--", relative):
                    raise ReceiverError("The immutable Git snapshot was modified; publication was refused.")
                return commit
        self._history_files(self.history / "sites" / record["bot_id"] / record["slug"], content)
        _write_json(destination, snapshot)
        self._git("add", "--", "sites/" + record["bot_id"] + "/" + record["slug"], relative)
        self._git(
            "commit",
            "-m",
            f"Publish {record['bot_id']}/{record['slug']} revision {record['revision']} ({record['job_id']})",
        )
        return self._git("rev-parse", "HEAD")

    def _receipt(self, record, site):
        current = self._record(site["current"]) if site.get("current") else None
        public = self.web / record["bot_id"] / record["slug"]
        visible = os.readlink(public) if public.is_symlink() else None
        pending = self._record(site["pending"]) if site.get("pending") else None
        if pending and visible == str(self._release_path(pending)):
            current = pending
        return {
            "version": 1,
            "delivered": record["status"] == "delivered",
            "delivery_current": (
                site.get("current") == record["job_id"]
                and record["status"] == "delivered"
                and visible == str(self._release_path(record))
            ),
            "bot_id": record["bot_id"],
            "slug": record["slug"],
            "revision": record["revision"],
            "job_id": record["job_id"],
            "remote_commit": record.get("remote_commit"),
            "manifest_hash": record["manifest_hash"],
            "status": record["status"],
            "current_revision": current["revision"] if current else None,
            "delivered_at": record.get("delivered_at"),
        }

    def _activate(self, record, site):
        self._verify_release(record)
        bot, slug = record["bot_id"], record["slug"]
        self._verify_pointer(bot, slug, site)
        site["pending"] = record["job_id"]
        self._save_site(bot, slug, site)
        public = self.web / bot / slug
        target = str(self._release_path(record))
        if not public.is_symlink() or os.readlink(public) != target:
            temporary = public.parent / (".publishing-" + secrets.token_hex(16))
            os.symlink(target, temporary)
            try:
                os.replace(temporary, public)
                _sync_directory(public.parent)
            finally:
                if temporary.is_symlink():
                    temporary.unlink()
        record.update(status="delivered", delivered_at=record.get("delivered_at") or now())
        _write_json(self._job_path(record["job_id"]), record)
        site.update(current=record["job_id"], pending=None)
        self._save_site(bot, slug, site)
        return self._receipt(record, site)

    def deploy(self, payload):
        requested, content = validate_envelope(payload)
        bot, slug, job = (requested[k] for k in ("bot_id", "slug", "job_id"))
        with self.locked():
            existing = self._record(job)
            if existing and existing["envelope_hash"] != requested["envelope_hash"]:
                raise ReceiverError(
                    "This job identifier is already reserved for different content or another bot."
                )
            self._namespace(bot, create=True)
            site = self._site(bot, slug, create=True)
            self._verify_pointer(bot, slug, site)
            current = self._record(site["current"]) if site.get("current") else None
            if current:
                self._verify_release(current)
            if existing and existing["status"] == "delivered":
                self._verify_release(existing)
                if site.get("pending") == job:
                    return self._activate(existing, site)
                return self._receipt(existing, site)
            if site.get("pending") and site["pending"] != job:
                raise ReceiverError(
                    "An earlier publication is incomplete; retry its existing job before a new revision."
                )
            if current and requested["revision"] <= current["revision"]:
                raise ReceiverError(
                    "This revision is stale; an older publication cannot replace the current site."
                )
            if current and not current["manifest"].keys() <= requested["manifest"].keys():
                raise ReceiverError(
                    "Published files cannot be deleted; include every previously published path."
                )
            other_bytes = 0
            for path in (self.metadata / "sites" / bot).glob("*.json"):
                other = _json(path)
                if other.get("slug") != slug and other.get("current"):
                    other_bytes += sum(
                        i["bytes"] for i in self._record(other["current"])["manifest"].values()
                    )
            if other_bytes + sum(i["bytes"] for i in requested["manifest"].values()) > MAX_BOT:
                raise ReceiverError("This bot has reached its remote published-byte limit.")
            record = existing or dict(requested, status="building")
            if not existing:
                _write_json(self._job_path(job), record)
            self._write_release(record, content)
            record["remote_commit"] = self._snapshot(record, content)
            record["status"] = "prepared"
            _write_json(self._job_path(job), record)
            return self._activate(record, site)

    def status(self, payload):
        if not isinstance(payload, dict) or payload.get("version") != 1:
            raise ReceiverError("Status needs version=1, bot_id, slug and an optional job_id.")
        bot, slug, job = (payload.get(k) for k in ("bot_id", "slug", "job_id"))
        if (
            not isinstance(bot, str)
            or not BOT_PATTERN.fullmatch(bot)
            or not isinstance(slug, str)
            or not SLUG_PATTERN.fullmatch(slug)
        ):
            raise ReceiverError("Status needs a valid bot_id and site slug.")
        if job is not None and (not isinstance(job, str) or not JOB_PATTERN.fullmatch(job)):
            raise ReceiverError("Status job_id must be a valid identifier.")
        with self.locked():
            site = self._site(bot, slug, create=False) if self._namespace(bot, create=False) else None
            if not site:
                return {
                    "version": 1,
                    "delivered": False,
                    "delivery_current": False,
                    "status": "unknown",
                    "bot_id": bot,
                    "slug": slug,
                    "job_id": job,
                }
            self._verify_pointer(bot, slug, site)
            record = (
                self._record(job or site.get("current") or site.get("pending"))
                if (job or site.get("current") or site.get("pending"))
                else None
            )
            if not record or record["bot_id"] != bot or record["slug"] != slug:
                return {
                    "version": 1,
                    "delivered": False,
                    "delivery_current": False,
                    "status": "unknown",
                    "bot_id": bot,
                    "slug": slug,
                    "job_id": job,
                }
            if record["status"] == "delivered":
                self._verify_release(record)
            return self._receipt(record, site)

    def audit(self):
        """Snapshot bounded drift evidence; never repair/adopt/replace public content."""
        with self.locked():
            observations, capture = [], {}
            for registration in sorted((self.metadata / "bots").glob("*.json")):
                bot = registration.stem
                if not BOT_PATTERN.fullmatch(bot):
                    raise ReceiverError("Invalid stored namespace identifier.")
                try:
                    self._namespace(bot, create=False)
                except (ReceiverError, OSError) as exc:
                    observations.append({"bot_id": bot, "issues": [str(exc)[:1000]]})
                    continue
                for path in sorted((self.metadata / "sites" / bot).glob("*.json")):
                    slug = path.stem
                    site = self._site(bot, slug, create=False)
                    issues = []
                    try:
                        self._verify_pointer(bot, slug, site)
                    except ReceiverError as exc:
                        issues.append(str(exc))
                    record = self._record(site["current"]) if site.get("current") else None
                    if record:
                        try:
                            drift, changed = self._inspect_release(record)
                            issues.extend(drift)
                            for name, data in changed.items():
                                capture[bot + "/" + slug + "/" + name] = data
                        except (ReceiverError, OSError) as exc:
                            issues.append(str(exc)[:1000])
                    observations.append(
                        {
                            "bot_id": bot,
                            "slug": slug,
                            "revision": record["revision"] if record else None,
                            "job_id": record["job_id"] if record else None,
                            "issues": issues,
                        }
                    )
            evidence = {
                "version": 1,
                "observations": observations,
                "captured": {p: {"blob": digest(b), "bytes": len(b)} for p, b in capture.items()},
            }
            observation_hash = digest(canonical(evidence))
            previous_path = self.metadata / "last-audit.json"
            previous = _json(previous_path) if previous_path.exists() else {}
            changed = previous.get("observation_hash") != observation_hash
            commit = previous.get("remote_commit")
            if changed:
                relative = "audits/" + observation_hash + ".json"
                _write_json(self.history / relative, dict(evidence, observed_at=now()))
                paths = [relative]
                if capture:
                    relative_drift = "drift/" + observation_hash
                    self._history_files(self.history / relative_drift, capture)
                    paths.append(relative_drift)
                self._git("add", "--", *paths)
                self._git("commit", "-m", "Audit static publications " + observation_hash[:12])
                commit = self._git("rev-parse", "HEAD")
            result = {
                "version": 1,
                "action": "audit",
                "checked_at": now(),
                "changed": changed,
                "sites_checked": sum("slug" in row for row in observations),
                "drift_count": sum(bool(row["issues"]) for row in observations),
                "observation_hash": observation_hash,
                "remote_commit": commit,
                "observations": observations,
            }
            _write_json(previous_path, result)
            return result


def _unique_object(items):
    result = {}
    for key, value in items:
        if key in result:
            raise ReceiverError("Duplicate JSON keys are not accepted.")
        result[key] = value
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--web-root", required=True)
    parser.add_argument("--state-root", required=True)
    parser.add_argument("action", choices=("deploy", "status", "audit"))
    args = parser.parse_args(argv)
    os.umask(0o077)
    try:
        receiver = Receiver(args.web_root, args.state_root)
        if args.action == "audit":
            result = receiver.audit()
        else:
            raw = sys.stdin.buffer.read(MAX_ENVELOPE + 1)
            if len(raw) > MAX_ENVELOPE:
                raise ReceiverError("Publish request exceeds the transport size limit.")
            try:
                payload = json.loads(raw, object_pairs_hook=_unique_object)
            except (ValueError, UnicodeDecodeError) as exc:
                raise ReceiverError("Request must contain valid JSON.") from exc
            result = getattr(receiver, args.action)(payload)
        print(json.dumps(result, sort_keys=True, allow_nan=False))
        return 0
    except (ReceiverError, OSError) as exc:
        message = (
            str(exc)
            if isinstance(exc, ReceiverError)
            else f"Publisher filesystem operation failed ({type(exc).__name__})."
        )
        print(json.dumps({"version": 1, "delivered": False, "error": message[:16000]}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
